version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: accounting-db
    environment:
      POSTGRES_USER: virt24474
      POSTGRES_PASSWORD: Huivoine
      POSTGRES_DB: accounting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 